version: "3.8"

services:
  user-service:
    build: ./submissions/user-service
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - node-app-network

  product-service:
    build: ./submissions/product-service
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - node-app-network

  order-service:
    build: ./submissions/order-service
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - node-app-network

  gateway-service:
    build: ./submissions/gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service
    restart: unless-stopped
    networks:
      - node-app-network

networks:
  node-app-network:
    driver: bridge
